# This generator creates a Secret from a gpg encrypted file
# (see file secrets.env.gpg, the passphrase is "example")
# The generated secret is named "jitsi-secrets" and merged with
# the one declared in the base component.
apiVersion: openfun
kind: GpgSecretGenerator
metadata:
  name: jitsi-secrets
argsOneLiner: ./secrets.env.gpg
