nodeSelector:
  k8s.scaleway.com/pool-name: default
prometheus:
  url: http://prometheus-operated.default.svc
  port: 9090
  path: ""
rules:
  default: false
  # The following rules define which prometheus metrics we want to expose
  # through Kubernetes custom metrics API. For more information, see :
  # https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/config.md
  custom:
  # The jibri_busy custom metric indicates if a jibri pod is busy (1) or not (0).
  # It can be queried manually with :
  # bin/kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/jibri/pods/*/jibri_busy
  # (value per pod in the jibri namespace)
  #
  # bin/kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/jibri/metrics/jibri_busy
  # (ratio of busy jibris for the whole jibri namespace)
  - seriesQuery: '{__name__="jibri_busystatus"}'
    resources:
      overrides:
        namespace:
          resource: namespace
    name:
      as: "jibri_busy"
    metricsQuery: sum(jibri_busystatus{<<.LabelMatchers>>}) by (<<.GroupBy>>) / count(jibri_busystatus{<<.LabelMatchers>>})  by (<<.GroupBy>>)
  # The network_transmit_bytes_last_5m custom metric indicates the bytes transmitted by pod.
  # It can be queried manually with :
  # bin/kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/jitsi/pods/*/network_transmit_bytes_last_5m"
  # (value per pod in the jitsi namespace)
  #
  # bin/kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/jitsi/metrics/network_transmit_bytes_last_5m
  # (total of bytes transmitted for the whole jitsi namespace)
  - seriesQuery: '{__name__="container_network_transmit_bytes_total"}'
    resources:
      overrides:
        namespace:
          resource: namespace
        pod:
          resource: pod
    name:
      as: "network_transmit_bytes_last_5m"
    metricsQuery: sum(rate(container_network_transmit_bytes_total{<<.LabelMatchers>>}[5m])) by (<<.GroupBy>>)
