# service for jvbs
# create service for jvb upd access on kubernetes Nodeport starting with 31000.
# Make sure NodePorts between 31000-31005 are available on your kube cluster.
# update this if you need JVBs more than 6.
# JVB-0
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb-0
  name: jvb-0
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - port: 30300
      name: jvb-0
      protocol: UDP
      targetPort: 30300
      nodePort: 30300
  selector:
    app: jvb
    "statefulset.kubernetes.io/pod-name": jvb-0
---
#JVB-1
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb-1
  name: jvb-1
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - port: 30301
      name: jvb-1
      protocol: UDP
      targetPort: 30301
      nodePort: 30301
  selector:
    app: jvb
    "statefulset.kubernetes.io/pod-name": jvb-1
---
#JVB-2
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb-2
  name: jvb-2
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - port: 30302
      name: jvb-2
      protocol: UDP
      targetPort: 30302
      nodePort: 30302
  selector:
    app: jvb
    "statefulset.kubernetes.io/pod-name": jvb-2
---
#JVB-3
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb-3
  name: jvb-3
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - port: 30303
      name: jvb-3
      protocol: UDP
      targetPort: 30303
      nodePort: 30303
  selector:
    app: jvb
    "statefulset.kubernetes.io/pod-name": jvb-3
---
#JVB-4
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb-4
  name:  jvb-4
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - port: 30304
      name:  jvb-4
      protocol: UDP
      targetPort: 30304
      nodePort: 30304
  selector:
    app: jvb
    "statefulset.kubernetes.io/pod-name":  jvb-4
---
#JVB-5
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb-5
  name:  jvb-5
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - port: 30305
      name:  jvb-5
      protocol: UDP
      targetPort: 30305
      nodePort: 30305
  selector:
    app: jvb
    "statefulset.kubernetes.io/pod-name":  jvb-5
