# The Jitsi Videobridge (JVB) component has some special behavior:
# - Each JVB container is publicly accessible on UDP port JVB_PORT (10000 by
#   default), on its node public IP address. This variable is initialized by
#   the entrypoint.sh script.
# - Each JVB pod is linked to a service created by the service-per-pod
#   DecoratorDontroller. The service exposes the JVB_PORT as a nodePort.
# - The JVB_PORT has to be different for each JVB and is thus calculated by
#   the following formula : basePort + index_of_the_pod_in_the_statefulset.
#   basePort is equal to 30300.
# - JVB pods are scheduled on the jvb nodepool, which have cluster autoscaling
#   enabled to add nodes when necessary
# - JVB opens a port to communicate with other JVBs with the OCTO protocol.
#   The port (JVB_OCTO_BIND_PORT, tcp 4096) is only accessible from within
#   the cluster. JVB advertises its internal IP to other JVB with the
#   environment variable JVB_OCTO_PUBLIC_ADDRESS, which is populated with
#   the fieldref status.podIP
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jvb
  labels:
    app: jvb
  # needed for metacontroller to create/delete service per pod
  annotations:
    service-per-pod-label: "statefulset.kubernetes.io/pod-name"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: jvb
  serviceName: jvb
  template:
    metadata:
      labels:
        app: jvb
    spec:
      volumes:
        - name: jvb-entrypoint
          configMap:
            name: jvb-entrypoint
            defaultMode: 0744 # make executable
      containers:
        - name: jvb
          image: "jitsi/jvb:stable-6865"
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: jitsi-common
          - configMapRef:
              name: jvb
          command:
            - /entrypoint/entrypoint.sh
          args:
            - "/init"
          volumeMounts:
            - name: jvb-entrypoint
              mountPath: /entrypoint
          env:
            - name: JVB_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: jitsi-secrets
                  key: JVB_AUTH_USER
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-secrets
                  key: JVB_AUTH_PASSWORD
            - name: JVB_OCTO_PUBLIC_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: octo
              containerPort: 4096
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /about/health
              port: 8080
          readinessProbe:
            httpGet:
              path: /about/health
              port: 8080
          resources:
            {}
      nodeSelector:
        k8s.scaleway.com/pool-name: jvb
