apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This part is widely inspired by https://github.com/metacontroller/metacontroller/tree/v2.2.5
# and https://github.com/hpi-schul-cloud/jitsi-deployment/tree/463ba815d3a18087e1e3b5bab9801699c5b31892

resources:
  - service-per-pod-deployment.yaml
  - metacontroller-rbac-patch.yaml

namespace: metacontroller

configMapGenerator:
- name: service-per-pod-hooks
  files:
    - service-per-pod-hooks/finalize-service-per-pod.jsonnet
    - service-per-pod-hooks/sync-service-per-pod.jsonnet
