apiVersion: apps/v1
kind: Deployment
metadata:
  name: jicofo
  labels:
    app: jicofo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jicofo
  template:
    metadata:
      labels:
        app: jicofo
    spec:
      containers:
        - name: jitsi-meet
          image: jitsi/jicofo:stable-6826
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: jitsi-common
          - configMapRef:
              name: jicofo
          env:
            - name: JICOFO_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: jitsi-secrets
                  key: JICOFO_AUTH_USER
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-secrets
                  key: JICOFO_AUTH_PASSWORD
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8888
          readinessProbe:
            tcpSocket:
              port: 8888
      nodeSelector:
        k8s.scaleway.com/pool-name: default
