apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: jigasi
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: jigasi
# These rules ensure that we can exec into the jigasi pod via Kubernetes API
# in order to launch the graceful shutdown once the pod is busy.
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/exec
    verbs:
    - get
    - post
    - list
    - patch
    - create
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: jigasi-jigasi
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: jigasi
  subjects:
  - kind: ServiceAccount
    name: jigasi
