apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi-meet-front
  labels:
    app: jitsi-meet-front
spec:
  selector:
    matchLabels:
      app: jitsi-meet-front
  template:
    metadata:
      labels:
        app: jitsi-meet-front
    spec:
      containers:
        - name: jitsi-meet
          image: "jitsi/web:stable-8044"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: jitsi-common
            - configMapRef:
                name: jitsi-meet-front
          env:
            - name: JICOFO_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: jitsi-secrets
                  key: JICOFO_AUTH_USER
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            limits:
              cpu: 2000m
              memory: 4000Mi
            requests:
              cpu: 1500m
              memory: 4000Mi
      nodeSelector:
        k8s.scaleway.com/pool-name: default
