apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: jvb-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jvb
  minReplicas: 20
  maxReplicas: 90
  behavior:
    # We'll allow to scale down 20% of the pods every 30s
    scaleDown:
      stabilizationWindowSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
