apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: jvb
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: jvb
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - list
    - patch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: jvb-jvb
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: jvb
  subjects:
  - kind: ServiceAccount
    name: jvb
