apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: jibri
    envs:
      - ./env/jibri.env
  - name: jitsi-common
    envs:
      - ./env/jitsi-common.env
  - name: jitsi-meet-front
    envs:
      - ./env/jitsi-meet-front.env
  - name: jicofo
    envs:
      - ./env/jicofo.env
  - name: jvb
    envs:
      - ./env/jvb.env
  - name: prosody
    envs:
      - ./env/prosody.env
  - name: jibri-metadata-updater
    files:
      - ./jibri-metadata-updater.py
  - name: jvb-metadata-updater
    files:
      - ./jvb-metadata-updater.py

namespace: jitsi

secretGenerator:
  - name: jitsi-secrets
    envs:
      - ./env/jitsi-secrets.env

resources:
  - cert-issuer.yml
  - jibri-deployment.yml
  - jibri-hpa.yaml
  - jibri-podmonitor.yml
  - jibri-service-account.yaml
  - jicofo-deployment.yml
  - jitsi-meet-front-deployment.yml
  - jitsi-meet-front-hpa.yml
  - jitsi-meet-front-ingress.yml
  - jitsi-meet-front-service.yml
  - jvb-hpa.yml
  - jvb-podmonitor.yml
  - jvb-service-account.yaml
  - jvb-deployment.yml
  - namespace.yml
  - prosody-deployment.yml
  - prosody-service.yml

replacements:
  # Replace the domain name configured in jitsi-meet-front Ingress with
  # the value XMPP_DOMAIN defined in the jitsi-common.env file
  - source:
      name: jitsi-common
      kind: ConfigMap
      version: v1
      fieldPath: data.XMPP_DOMAIN
    targets:
      - select:
          kind: Ingress
          name: jitsi-meet-front
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
